name: Build

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.3'  # Adjust to your Flutter version

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'  # or the version compatible with SpectralOps

    - name: Run SpectralOps SAST tool
      run: echo "Sast Tool"

    - name: Run DockerFile
      run: echo "DockerFiles"


    - name: Deploy to cloud Kubernetes cluster
      run: echo "hello"
