name: Build

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.3'  

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'  # or the version compatible with SpectralOps

    - name: Install SpectralOps
      run: npm install -g spectralops
  
    - name: Run SpectralOps
      run: spectralops analyze

    - name: Run DockerFile
      run: |
        docker build -t architerravisiion:latest .
        docker run -it --rm architerravisiion:latest


    - name: Deploy to cloud Kubernetes cluster
      run: echo "hello"
