name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.3'  # Replace with your desired Flutter version
        channel: 'stable'
        cache: false

    - name: Install dependencies
      run: flutter pub get

    - name: Build project
      run: flutter build apk --release

    - name: Static analysis with semgrep
      run: semgrep --config=p/security

 
