name: Flutter Pub Get

on:
  push:
    branches:
      - main

jobs:
  flutter_pub_get:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.0'  # Replace with your desired Flutter version
    
    - name: Flutter Pub Get
      run: flutter pub get
